// Scraped from itch.io Solana Speedrun 3 - 2025-07-18T06:16:17.506Z
const speedrun2024Games: Project[] = [
  {
    id: 'speedrun-1',
    project_name: 'Game 1',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-1',
    video_url: '',
    created_at: '2024-01-19T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-2',
    project_name: 'Game 2',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-2',
    video_url: '',
    created_at: '2024-01-18T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-3',
    project_name: 'Game 3',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-3',
    video_url: '',
    created_at: '2024-01-17T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-4',
    project_name: 'Game 4',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-4',
    video_url: '',
    created_at: '2024-01-16T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-5',
    project_name: 'Game 5',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-5',
    video_url: '',
    created_at: '2024-01-15T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-6',
    project_name: 'Game 6',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-6',
    video_url: '',
    created_at: '2024-01-14T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-7',
    project_name: 'Game 7',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-7',
    video_url: '',
    created_at: '2024-01-13T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-8',
    project_name: 'Game 8',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-8',
    video_url: '',
    created_at: '2024-01-12T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-9',
    project_name: 'Game 9',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-9',
    video_url: '',
    created_at: '2024-01-11T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-10',
    project_name: 'Game 10',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-10',
    video_url: '',
    created_at: '2024-01-10T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-11',
    project_name: 'Game 11',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-11',
    video_url: '',
    created_at: '2024-01-09T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-12',
    project_name: 'Game 12',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-12',
    video_url: '',
    created_at: '2024-01-08T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-13',
    project_name: 'Game 13',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop',
    screenshot_urls: ['https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=400&fit=crop'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-13',
    video_url: '',
    created_at: '2024-01-07T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-14',
    project_name: 'Game 14',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-14',
    video_url: '',
    created_at: '2024-01-06T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-15',
    project_name: 'Game 15',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-15',
    video_url: '',
    created_at: '2024-01-05T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-16',
    project_name: 'Game 16',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-16',
    video_url: '',
    created_at: '2024-01-04T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-17',
    project_name: 'Game 17',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-17',
    video_url: '',
    created_at: '2024-01-03T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-18',
    project_name: 'Game 18',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-18',
    video_url: '',
    created_at: '2024-01-02T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-19',
    project_name: 'Game 19',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-19',
    video_url: '',
    created_at: '2024-01-01T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-20',
    project_name: 'Game 20',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-20',
    video_url: '',
    created_at: '2023-12-31T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-21',
    project_name: 'Game 21',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-21',
    video_url: '',
    created_at: '2023-12-30T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-22',
    project_name: 'Game 22',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-22',
    video_url: '',
    created_at: '2023-12-29T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-23',
    project_name: 'Game 23',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-23',
    video_url: '',
    created_at: '2023-12-28T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-24',
    project_name: 'Game 24',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-24',
    video_url: '',
    created_at: '2023-12-27T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-25',
    project_name: 'Game 25',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-25',
    video_url: '',
    created_at: '2023-12-26T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-26',
    project_name: 'Game 26',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-26',
    video_url: '',
    created_at: '2023-12-25T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-27',
    project_name: 'Game 27',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-27',
    video_url: '',
    created_at: '2023-12-24T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-28',
    project_name: 'Game 28',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-28',
    video_url: '',
    created_at: '2023-12-23T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  },
  {
    id: 'speedrun-29',
    project_name: 'Game 29',
    project_description: 'Game by Unknown from Solana Speedrun 3...',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3'],
    banner_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop',
    screenshot_urls: ['https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=400&fit=crop'],
    game_host_url: '',
    github_url: 'https://github.com/unknown/game-29',
    video_url: '',
    created_at: '2023-12-22T00:00:00.000Z',
    creator_profile: { full_name: 'Unknown', avatar_url: null }
  }
];

