// Scraped from itch.io Solana Speedrun 3 - 2025-07-18T06:18:25.317Z
const speedrun2024Games: Project[] = [
  {
    id: 'speedrun-1',
    project_name: 'Back to the World',
    project_description: 'Game by TahaErel from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1MzI5LmpwZw==/300x240%23c/k0SBg%2B.jpg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/tahaerel/back-to-the-world',
    video_url: '',
    created_at: '2024-01-19T00:00:00.000Z',
    creator_profile: { full_name: 'TahaErel', avatar_url: null }
  },
  {
    id: 'speedrun-2',
    project_name: 'Last Forever',
    project_description: 'Game by JonasHahn from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NjgzLnBuZw==/300x240%23c/%2BqwiKP.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/jonashahn/last-forever',
    video_url: '',
    created_at: '2024-01-18T00:00:00.000Z',
    creator_profile: { full_name: 'JonasHahn', avatar_url: null }
  },
  {
    id: 'speedrun-3',
    project_name: 'Imephemerals',
    project_description: 'Game by val-samonte from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEzNTM0LnBuZw==/300x240%23c/JKq1dx.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/valsamonte/imephemerals',
    video_url: '',
    created_at: '2024-01-17T00:00:00.000Z',
    creator_profile: { full_name: 'val-samonte', avatar_url: null }
  },
  {
    id: 'speedrun-4',
    project_name: 'Degen Adventures',
    project_description: 'Game by Grrwahrr from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'RPG/MMORPG',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODMyMzM5LnBuZw==/300x240%23c/xEMnxV.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/grrwahrr/degen-adventures',
    video_url: '',
    created_at: '2024-01-16T00:00:00.000Z',
    creator_profile: { full_name: 'Grrwahrr', avatar_url: null }
  },
  {
    id: 'speedrun-5',
    project_name: 'Endless Tower - Solana Speedrun 3',
    project_description: 'Game by Kaleve from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Strategy',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2NzkwMzk2LnBuZw==/300x240%23c/GH8s%2FY.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/kaleve/endless-tower-solana-speedrun-3',
    video_url: '',
    created_at: '2024-01-15T00:00:00.000Z',
    creator_profile: { full_name: 'Kaleve', avatar_url: null }
  },
  {
    id: 'speedrun-6',
    project_name: 'ValhallaVerse Arena Mode',
    project_description: 'Game by koe1k from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEyMTQ4LnBuZw==/300x240%23c/EzbdQJ.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/koe1k/valhallaverse-arena-mode',
    video_url: '',
    created_at: '2024-01-14T00:00:00.000Z',
    creator_profile: { full_name: 'koe1k', avatar_url: null }
  },
  {
    id: 'speedrun-7',
    project_name: 'Airdrops Forever',
    project_description: 'Game by venusv from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Casual/Mobile',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3Mjc2LnBuZw==/300x240%23c/W2nvGI.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/venusv/airdrops-forever',
    video_url: '',
    created_at: '2024-01-13T00:00:00.000Z',
    creator_profile: { full_name: 'venusv', avatar_url: null }
  },
  {
    id: 'speedrun-8',
    project_name: 'Partner | Solana Visual Novel',
    project_description: 'Game by wanaoki from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Educational',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3MTAzLmpwZw==/300x240%23c/EUCjj%2F.jpg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/wanaoki/partner-solana-visual-novel',
    video_url: '',
    created_at: '2024-01-12T00:00:00.000Z',
    creator_profile: { full_name: 'wanaoki', avatar_url: null }
  },
  {
    id: 'speedrun-9',
    project_name: 'Foothold by Multisynq',
    project_description: 'Game by Multisynq from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE5Mjc5LnBuZw==/300x240%23c/rsbcnS.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/multisynq/foothold-by-multisynq',
    video_url: '',
    created_at: '2024-01-11T00:00:00.000Z',
    creator_profile: { full_name: 'Multisynq', avatar_url: null }
  },
  {
    id: 'speedrun-10',
    project_name: 'Solana Science',
    project_description: 'Game by Virus-Axel from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Educational',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2Mzg4LnBuZw==/300x240%23c/KUgGXQ.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/virusaxel/solana-science',
    video_url: '',
    created_at: '2024-01-10T00:00:00.000Z',
    creator_profile: { full_name: 'Virus-Axel', avatar_url: null }
  },
  {
    id: 'speedrun-11',
    project_name: 'Boxtraining',
    project_description: 'Game by aleylekoglu from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2OTA4LnBuZw==/300x240%23c/obB6NK.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/aleylekoglu/boxtraining',
    video_url: '',
    created_at: '2024-01-09T00:00:00.000Z',
    creator_profile: { full_name: 'aleylekoglu', avatar_url: null }
  },
  {
    id: 'speedrun-12',
    project_name: 'Manic Entanglement',
    project_description: 'Game by Rit Rafa from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Puzzle',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NTY3LnBuZw==/300x240%23c/hMyyXZ.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/ritrafa/manic-entanglement',
    video_url: '',
    created_at: '2024-01-08T00:00:00.000Z',
    creator_profile: { full_name: 'Rit Rafa', avatar_url: null }
  },
  {
    id: 'speedrun-13',
    project_name: 'ephesus',
    project_description: 'Game by 0xa1f13 from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop',
    screenshot_urls: ['https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=400&fit=crop'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/0xa1f13/ephesus',
    video_url: '',
    created_at: '2024-01-07T00:00:00.000Z',
    creator_profile: { full_name: '0xa1f13', avatar_url: null }
  },
  {
    id: 'speedrun-14',
    project_name: 'The Last Sea Turtle',
    project_description: 'Game by solanagirl from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Educational',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3OTI0LmpwZw==/300x240%23c/9TPsV%2B.jpg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/solanagirl/the-last-sea-turtle',
    video_url: '',
    created_at: '2024-01-06T00:00:00.000Z',
    creator_profile: { full_name: 'solanagirl', avatar_url: null }
  },
  {
    id: 'speedrun-15',
    project_name: 'NFTactics',
    project_description: 'Game by David Alexander Pfeiffer from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Strategy',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3OTE5LnBuZw==/300x240%23c/vq4oI1.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/davidalexanderpfeiffer/nftactics',
    video_url: '',
    created_at: '2024-01-05T00:00:00.000Z',
    creator_profile: { full_name: 'David Alexander Pfeiffer', avatar_url: null }
  },
  {
    id: 'speedrun-16',
    project_name: 'BlinkBash!',
    project_description: 'Game by daoplays from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE0NzMzLnBuZw==/300x240%23c/N%2BJiKf.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/daoplays/blinkbash-',
    video_url: '',
    created_at: '2024-01-04T00:00:00.000Z',
    creator_profile: { full_name: 'daoplays', avatar_url: null }
  },
  {
    id: 'speedrun-17',
    project_name: 'TVT RPG',
    project_description: 'Game by TranSiTien from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'RPG/MMORPG',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NzI5LnBuZw==/300x240%23c/S7NZ4O.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/transitien/tvt-rpg',
    video_url: '',
    created_at: '2024-01-03T00:00:00.000Z',
    creator_profile: { full_name: 'TranSiTien', avatar_url: null }
  },
  {
    id: 'speedrun-18',
    project_name: '2048 Puzzle Game on Solana',
    project_description: 'Game by tolgahanbora from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Puzzle',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NzQ2LnBuZw==/300x240%23c/nxAATU.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/tolgahanbora/2048-puzzle-game-on-solana',
    video_url: '',
    created_at: '2024-01-02T00:00:00.000Z',
    creator_profile: { full_name: 'tolgahanbora', avatar_url: null }
  },
  {
    id: 'speedrun-19',
    project_name: '50 Shades of Charity',
    project_description: 'Game by TED3166 from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Educational',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1NDEwLnBuZw==/300x240%23c/454TY5.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/ted3166/50-shades-of-charity',
    video_url: '',
    created_at: '2024-01-01T00:00:00.000Z',
    creator_profile: { full_name: 'TED3166', avatar_url: null }
  },
  {
    id: 'speedrun-20',
    project_name: 'sms02-swapmystyle02',
    project_description: 'Game by vetsinen from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Simulation',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODEzNjQ0LmpwZw==/300x240%23c/3OgrxN.jpg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/vetsinen/sms02-swapmystyle02',
    video_url: '',
    created_at: '2023-12-31T00:00:00.000Z',
    creator_profile: { full_name: 'vetsinen', avatar_url: null }
  },
  {
    id: 'speedrun-21',
    project_name: 'Solara\'s realm',
    project_description: 'Game by emirhan3699 from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1NTI5LnBuZw==/300x240%23c/oWQaG6.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/emirhan3699/solara-s-realm',
    video_url: '',
    created_at: '2023-12-30T00:00:00.000Z',
    creator_profile: { full_name: 'emirhan3699', avatar_url: null }
  },
  {
    id: 'speedrun-22',
    project_name: 'Rexagotchi',
    project_description: 'Game by r3xap from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Casual/Mobile',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3NTkwLmpwZWc=/300x240%23c/FZz1qw.jpeg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/r3xap/rexagotchi',
    video_url: '',
    created_at: '2023-12-29T00:00:00.000Z',
    creator_profile: { full_name: 'r3xap', avatar_url: null }
  },
  {
    id: 'speedrun-23',
    project_name: 'Mining Badger [Honeycomb x CIVIC]',
    project_description: 'Game by chiefbee from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Simulation',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3ODI4LmpwZw==/300x240%23c/T%2Bf6H4.jpg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/chiefbee/mining-badger-honeycomb-x-civic-',
    video_url: '',
    created_at: '2023-12-28T00:00:00.000Z',
    creator_profile: { full_name: 'chiefbee', avatar_url: null }
  },
  {
    id: 'speedrun-24',
    project_name: 'Arena Survivor',
    project_description: 'Game by truongnguyenptn from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE4MDA0LmpwZWc=/300x240%23c/dvFH6u.jpeg'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/truongnguyenptn/arena-survivor',
    video_url: '',
    created_at: '2023-12-27T00:00:00.000Z',
    creator_profile: { full_name: 'truongnguyenptn', avatar_url: null }
  },
  {
    id: 'speedrun-25',
    project_name: 'Echoes Of Eldoria',
    project_description: 'Game by Eldahalas from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'RPG/MMORPG',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NzgyLnBuZw==/300x240%23c/Su%2F%2BRN.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/eldahalas/echoes-of-eldoria',
    video_url: '',
    created_at: '2023-12-26T00:00:00.000Z',
    creator_profile: { full_name: 'Eldahalas', avatar_url: null }
  },
  {
    id: 'speedrun-26',
    project_name: 'Nuke-Foot-Cockroach',
    project_description: 'Game by Blockiosaurus from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Action/Adventure',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE1MDUzLnBuZw==/300x240%23c/ORd5rJ.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/blockiosaurus/nuke-foot-cockroach',
    video_url: '',
    created_at: '2023-12-25T00:00:00.000Z',
    creator_profile: { full_name: 'Blockiosaurus', avatar_url: null }
  },
  {
    id: 'speedrun-27',
    project_name: 'Eternal Gauntlet',
    project_description: 'Game by Suzamaki from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'RPG/MMORPG',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE3MjAwLnBuZw==/300x240%23c/cHCUZA.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/suzamaki/eternal-gauntlet',
    video_url: '',
    created_at: '2023-12-24T00:00:00.000Z',
    creator_profile: { full_name: 'Suzamaki', avatar_url: null }
  },
  {
    id: 'speedrun-28',
    project_name: 'Startup',
    project_description: 'Game by dwrx from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Simulation',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png',
    logo_url: 'https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png',
    screenshot_urls: ['https://img.itch.zone/aW1nLzE2ODE2NjkzLnBuZw==/300x240%23c/QETeyv.png'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/dwrx/startup',
    video_url: '',
    created_at: '2023-12-23T00:00:00.000Z',
    creator_profile: { full_name: 'dwrx', avatar_url: null }
  },
  {
    id: 'speedrun-29',
    project_name: 'Codename : FutureSport',
    project_description: 'Game by nevernotplay from Solana Speedrun 3 hackathon. Innovative blockchain gaming experience.',
    category: 'Sports',
    tech_stack: ['Solana', 'Web3', 'JavaScript', 'TypeScript'],
    banner_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop',
    logo_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop',
    screenshot_urls: ['https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=400&fit=crop'],
    game_host_url: 'https://itch.io/jam/solana-speedrun-3/entries',
    github_url: 'https://github.com/nevernotplay/codename-futuresport',
    video_url: '',
    created_at: '2023-12-22T00:00:00.000Z',
    creator_profile: { full_name: 'nevernotplay', avatar_url: null }
  }
];